Repository ChainSafe/PINT, pull requests merged in 2021-11, with the labels that each got.

#444 chore(deps): update to polkadot-v0.9.12
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/polkadot.rs
  node/src/client.rs
  node/src/command.rs
  node/src/instant_finalize.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/service.rs
  pallets/asset-index/Cargo.toml
  pallets/asset-index/rpc/Cargo.toml
  pallets/asset-index/rpc/runtime-api/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/types.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
  pallets/local-treasury/Cargo.toml
  pallets/local-treasury/src/lib.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/types.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/types.rs
  pallets/remote-treasury/Cargo.toml
  pallets/remote-treasury/src/lib.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  primitives/primitives/Cargo.toml
  primitives/primitives/src/fee.rs
  primitives/primitives/src/types.rs
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/assets.rs
  primitives/xcm-calls/src/lib.rs
  primitives/xcm-calls/src/proxy.rs
  primitives/xcm-calls/src/staking.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/lib.rs
  runtime/integration-tests/src/pint.rs
  runtime/integration-tests/src/relay.rs
  runtime/integration-tests/src/statemint.rs
  runtime/integration-tests/src/tests.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: needs changes

#448 feat: add asset tx payments
  Cargo.lock
  pallets/asset-index/Cargo.toml
  pallets/saft-registry/Cargo.toml
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/payment.rs
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  test-utils/xcm-test-support/Cargo.toml
Labels: needs review

#451 chore(runtime): update runtime names
  Cargo.lock
  node/Cargo.toml
  node/src/chain_spec/dev.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/pint.rs
  node/src/chain_spec/shot.rs
  node/src/client.rs
  node/src/command.rs
  node/src/service.rs
  rpc/Cargo.toml
  runtime/common/Cargo.toml
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/integration-tests/Cargo.toml
  runtime/integration-tests/src/pint.rs
  runtime/pint/Cargo.toml
  runtime/pint/build.rs
  runtime/pint/src/lib.rs
  runtime/shot/Cargo.toml
  runtime/shot/build.rs
  runtime/shot/src/lib.rs
Labels: approved

#460 feat: add pallet-utility
  Cargo.lock
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/pint/Cargo.toml
  runtime/pint/src/lib.rs
  runtime/shot/Cargo.toml
  runtime/shot/src/lib.rs
Labels: approved

#450 feat(e2e): upgrade e2e tests for polkadot-v0.9.12
  config.json
  js/e2e/package.json
  js/e2e/yarn.lock
  js/pint-types-bundle/package.json
  js/pint-types-bundle/yarn.lock
  js/yarn.lock
  yarn.lock
Labels: needs review
