Repository ChainSafe/PINT, pull requests merged in 2021-08, with the labels that each got.

#241 feat(runtime): construct pint runtimes for kusama and polkadot
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/mod.rs
  node/src/chain_spec/polkadot.rs
  node/src/client.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/service.rs
  primitives/primitives/src/fee.rs
  primitives/primitives/src/lib.rs
  primitives/primitives/src/types.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/lib.rs
  runtime/common/src/weights/mod.rs
  runtime/common/src/weights/pallet_asset_index.rs
  runtime/common/src/weights/pallet_chainlink_feed.rs
  runtime/common/src/weights/pallet_committee.rs
  runtime/common/src/weights/pallet_local_treasury.rs
  runtime/common/src/weights/pallet_price_feed.rs
  runtime/common/src/weights/pallet_remote_asset_manager.rs
  runtime/common/src/weights/pallet_saft_registry.rs
  runtime/dev/Cargo.toml
  runtime/dev/build.rs
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/build.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/build.rs
  runtime/polkadot/src/lib.rs
  runtime/src/constants.rs
  runtime/src/weights/mod.rs
Labels: approved

#247 perf: simplify price feed pallet
  Cargo.lock
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/price-feed/src/types.rs
  runtime/common/Cargo.toml
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: approved

#231 refactor(asset-index): improve complete withdrawal and asset redemption
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/types.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/types.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
Labels: approved

#249 feat: abstract all NAV related calculations over NavProvider trait
  pallets/asset-index/src/lib.rs
  primitives/primitives/src/traits.rs
Labels: needs review

#253 style(rustfmt): imports_granularity=Crate && wrap_comments=true
  node/src/client.rs
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
  pallets/local-treasury/src/mock.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/tests.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/tests.rs
  primitives/xcm-calls/src/lib.rs
  primitives/xcm-calls/src/staking.rs
  runtime/common/src/constants.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  test-utils/xcm-test-support/src/lib.rs
Labels: needs review

#258 feat(saft): use saft identifiers instead of indices
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/traits.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/tests.rs
  primitives/primitives/src/traits.rs
  primitives/primitives/src/types.rs
  runtime/common/src/weights/pallet_saft_registry.rs
Labels: needs review

#257 refactor: use consistent nav terminology
  Cargo.lock
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/types.rs
  pallets/committee/src/tests.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/tests.rs
  pallets/price-feed/src/traits.rs
  pallets/price-feed/src/types.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  primitives/primitives/src/types.rs
  resources/types.json
  runtime/common/src/constants.rs
  runtime/common/src/weights/pallet_asset_index.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#259 feat: simplify price feeds and redemption process
  Cargo.lock
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/types.rs
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/price-feed/src/tests.rs
  pallets/price-feed/src/traits.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  primitives/primitives/src/types.rs
  runtime/common/src/weights/pallet_price_feed.rs
Labels: needs review

#264 style: simplify redemption calls and more docs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/traits.rs
  pallets/asset-index/src/types.rs
Labels: needs review

#262 feat(benchmarks): complete benchmarks of pallet asset-index
  .dockerignore
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
Labels: approved

#265 feat: improve remote staking
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/polkadot.rs
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/staking.rs
  runtime/common/src/constants.rs
Labels: needs review

#282 feat: simplify redemption statemachine
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/types.rs
Labels: approved, break-api

#269 feat(e2e): Complete js types and fix e2e tests
  js/e2e/index.ts
  js/e2e/src/extrinsic.ts
  js/e2e/src/runner.ts
  js/pint-types-bundle/index.ts
Labels: approved

#286 feat(e2e): adds WithdrawalsPeriod for the complete_withdraw call
  js/e2e/index.ts
  js/pint-types-bundle/index.ts
Labels: needs review, e2e

#287 feat(e2e): updates the verification part of pallet remote-asset-manager
  js/e2e/index.ts
  js/pint-types-bundle/index.ts
Labels: needs review

#288 feat(asset-index): mint asset into the treasury account in add_asset call
  pallets/asset-index/src/lib.rs
  pallets/remote-asset-manager/src/tests.rs
Labels: approved

#284 feat: handle xcm staking calls on a per block basis
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/remote-asset-manager/src/traits.rs
  pallets/remote-asset-manager/src/types.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  runtime/common/src/constants.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: approved, WIP, new-api

#291 feat: update statemint xcm support
  js/pint-types-bundle/index.ts
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/remote-asset-manager/src/types.rs
  runtime/common/src/constants.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
  test-utils/xcm-test-support/src/lib.rs
Labels: needs review

#298 ci(header): fix check-license
  .github/workflows/check-licence.yml
Labels: needs review

#299 chore(asset-index): extend weights for pallet asset-index
  pallets/asset-index/src/lib.rs
  runtime/common/src/weights/pallet_asset_index.rs
Labels: needs review

#297 feat: add rpc and runtime api crates
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/service.rs
  pallets/asset-index/rpc/Cargo.toml
  pallets/asset-index/rpc/runtime-api/Cargo.toml
  pallets/asset-index/rpc/runtime-api/src/lib.rs
  pallets/asset-index/rpc/src/lib.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: approved

#295 chore: upgrade to polkadot v0.9.9 and xcm
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/client.rs
  node/src/service.rs
  pallets/asset-index/Cargo.toml
  pallets/asset-index/rpc/Cargo.toml
  pallets/asset-index/rpc/runtime-api/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  pallets/local-treasury/Cargo.toml
  pallets/local-treasury/src/mock.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/mock.rs
  pallets/saft-registry/src/tests.rs
  primitives/primitives/Cargo.toml
  primitives/primitives/src/traits.rs
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/lib.rs
  primitives/xcm-calls/src/proxy.rs
  rpc/Cargo.toml
  rpc/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/constants.rs
  runtime/common/src/weights/pallet_chainlink_feed.rs
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
  test-utils/xcm-test-support/Cargo.toml
  test-utils/xcm-test-support/src/relay.rs
  tree.txt
Labels: approved

#304 chore: remove tree file
  tree.txt
Labels: needs review

#306 chore(ci): test all crates but all-features only for dev runtime
  .circleci/config.yml
Labels: needs review

#305 feat(runtime): checking and renaming origins for all pallets
  pallets/asset-index/src/lib.rs
  runtime/common/src/lib.rs
  runtime/common/src/types.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#300 feat(runtime): use committee origin for pallet asset-index
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/traits.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/mock.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs changes

#308 fix: remove some AssetId bounds and add TryFrom<u8>
  Cargo.lock
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/traits.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/mock.rs
Labels: needs changes
