Repository ChainSafe/PINT, pull requests merged in 2021-09, with the labels that each got.

#312 feat(node): remove polkadot-test-service
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
Labels: needs review

#315 feat(runtime): list benchmarks for all runtimes
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#313 chore: typos and docs
  pallets/local-treasury/src/lib.rs
Labels: approved

#320 feat: add default remote asset manager impl
  pallets/asset-index/src/mock.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
Labels: needs review

#294 feat(asset-index): timestamp deposits
  node/src/service.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  runtime/common/src/constants.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: approved

#316 feat: add MaybeAssetIdConvert trait for runtime benchmarks
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  primitives/primitives/Cargo.toml
  primitives/primitives/src/traits.rs
  primitives/primitives/src/types.rs
  runtime/dev/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
Labels: needs review

#321 feat: add xcm remote treasury pallet
  Cargo.lock
  pallets/local-treasury/src/lib.rs
  pallets/remote-treasury/Cargo.toml
  pallets/remote-treasury/README.md
  pallets/remote-treasury/src/lib.rs
Labels: needs review

#322 feat: add remote treasury to runtime
  Cargo.lock
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/traits.rs
  pallets/remote-treasury/src/lib.rs
  pallets/saft-registry/src/mock.rs
  runtime/dev/Cargo.toml
  runtime/dev/src/lib.rs
  runtime/kusama/Cargo.toml
  runtime/kusama/src/lib.rs
  runtime/polkadot/Cargo.toml
  runtime/polkadot/src/lib.rs
Labels: approved

#327 Fix benchmarks of saft-registry
  node/src/chain_spec/dev.rs
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/mock.rs
  primitives/primitives/src/traits.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#329 feat(runtime): regenerate weights for pallets
  pallets/local-treasury/src/benchmarking.rs
  pallets/saft-registry/src/benchmarking.rs
  runtime/common/src/weights/pallet_asset_index.rs
  runtime/common/src/weights/pallet_committee.rs
  runtime/common/src/weights/pallet_local_treasury.rs
  runtime/common/src/weights/pallet_price_feed.rs
  runtime/common/src/weights/pallet_saft_registry.rs
Labels: approved

#336 feat: add index token deposit range
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/types.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/mock.rs
  resources/types.json
  runtime/common/src/constants.rs
  runtime/common/src/weights/pallet_asset_index.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: approved

#332 feat(docs): Adds mkdocs for project documentation
  .github/workflows/docs.yml
  README.md
  docs/.gitignore
  docs/404.html
  docs/assets/css/style.scss
  docs/assets/favicon.ico
  docs/assets/img/nav-formula.png
  docs/assets/img/pint.png
  docs/assets/pint2.svg
  docs/getting-started/installation.md
  docs/getting-started/overview/architecture.md
  docs/getting-started/resources/developer-resources.md
  docs/getting-started/resources/general-resources.md
  docs/index.md
  docs/usage/command-line.md
  docs/usage/configuration.md
  mkdocs.yml
  resources/README.md
  resources/types.json
Labels: WIP

#339 feat(js): adds scripts in js directory
  js/package.json
  js/pint-types-bundle/package.json
  js/scripts/update_pint_types.ts
  resources/types.json
Labels: needs review

#341 chore(docs): add more chain spec info
  docs/usage/command-line.md
  resources/README.md
  resources/pint-dev-with-chainlink-feed.json
  resources/pint-dev.json
Labels: needs review

#340 chore: upgrade chainlink pallet
  Cargo.lock
  docs/usage/configuration.md
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/polkadot.rs
  pallets/asset-index/Cargo.toml
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/mock.rs
  runtime/common/Cargo.toml
  runtime/dev/Cargo.toml
  runtime/kusama/Cargo.toml
  runtime/polkadot/Cargo.toml
Labels: needs review

#334 feat: make --dev work standalone
  README.md
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/polkadot.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
Labels: needs review

#342 chore(docs): add more pallet docs
  pallets/asset-index/src/lib.rs
  pallets/committee/src/lib.rs
  pallets/local-treasury/src/lib.rs
  pallets/saft-registry/src/lib.rs
Labels: needs review

#345 chore(docs): add custom types image
  docs/assets/img/set-custom-types.png
  docs/usage/configuration.md
Labels: needs review

#346 feat(e2e): fix pallet asset-index and committee in e2e tests
  js/e2e/index.ts
  js/e2e/src/extrinsic.ts
Labels: needs review

#348 chore(docs): add more docs and fix typos
  pallets/asset-index/src/lib.rs
  pallets/saft-registry/src/lib.rs
  primitives/primitives/src/fee.rs
  primitives/primitives/src/traits.rs
  primitives/xcm-calls/src/encode_with.rs
  primitives/xcm-calls/src/lib.rs
  primitives/xcm-calls/src/proxy.rs
  primitives/xcm-calls/src/staking.rs
  resources/README.md
Labels: needs review

#350 fix: determine the index token euqivalent when removing a saft
  pallets/asset-index/src/lib.rs
Labels: approved

#335 feat: add root calls
  pallets/asset-index/src/lib.rs
  pallets/saft-registry/src/lib.rs
Labels: needs review

#353 feat(e2e): add shortcut for proposing extrinsic
  js/e2e/index.ts
  js/e2e/src/config.ts
  js/e2e/src/extrinsic.ts
  js/e2e/src/runner.ts
  js/pint-types-bundle/index.ts
  runtime/dev/src/lib.rs
Labels: needs review

#359 feat(e2e): apply admin origin to e2e tests
  js/e2e/index.ts
  js/e2e/src/config.ts
  js/e2e/src/extrinsic.ts
  js/e2e/src/runner.ts
  js/pint-types-bundle/index.ts
Labels: needs review

#358 feat: add freeze and thaw extrinsics
  node/src/chain_spec/dev.rs
  node/src/chain_spec/kusama.rs
  node/src/chain_spec/polkadot.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  primitives/xcm-calls/src/staking.rs
  runtime/common/src/weights/pallet_remote_asset_manager.rs
Labels: approved

#379 fix: rename Vote type
  js/e2e/src/extrinsic.ts
  js/pint-types-bundle/index.ts
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
  resources/types.json
Labels: approved, break-api

#381 fix: ensure non empty metadata
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/tests.rs
Labels: needs review

#380 feat: determine weight for upkeep and log error case
  Cargo.lock
  pallets/committee/Cargo.toml
  pallets/committee/src/lib.rs
Labels: needs review

#385 fix: make zero amount transfers noops
  pallets/remote-treasury/src/lib.rs
Labels: approved

#384 feat(committee): only members can submit proposals
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#388 feat(ci): test benchmarks in CI
  .circleci/config.yml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/saft-registry/src/benchmarking.rs
  primitives/primitives/src/traits.rs
Labels: approved

#390 feat(asset-index): add check for decimals of asset metadata
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/saft-registry/src/mock.rs
  runtime/common/src/constants.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#391 fix: relative img path
  docs/getting-started/overview/architecture.md
Labels: approved

#400 feat(weight): update dispatch class for important calls
  pallets/committee/src/lib.rs
Labels: needs review

#399 feat(committee): add remove member call
  js/e2e/index.ts
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  runtime/common/src/constants.rs
  runtime/common/src/weights/pallet_committee.rs
Labels: approved

#387 feat(asset-index): split off add_asset
  js/e2e/index.ts
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/tests.rs
  pallets/remote-asset-manager/src/tests.rs
  pallets/saft-registry/src/mock.rs
Labels: approved

#416 feat: include SaftRecord in events
  pallets/saft-registry/src/lib.rs
Labels: needs review

#406 feat(committee): introduce storage VotingTimeouts
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
Labels: needs review

#410 feat(committee): refactor Proposal and add timeout
  js/pint-types-bundle/index.ts
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
  resources/types.json
Labels: approved

#419 feat(committee): testing new members cannot vote
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
Labels: needs review

#421 feat(committee): move VotingPeriod to storage
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  runtime/common/src/constants.rs
  runtime/common/src/weights/pallet_committee.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: approved

#423 Execute proposals with original issuers
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
  runtime/common/src/weights/pallet_committee.rs
Labels: needs review

#429 feat(committee): introduce VotingPeriodRange
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/traits.rs
  runtime/common/src/types.rs
  runtime/dev/src/lib.rs
  runtime/kusama/src/lib.rs
  runtime/polkadot/src/lib.rs
Labels: needs review

#424 feat(committee): introduce PendingVotingPeriod
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  runtime/common/src/weights/pallet_committee.rs
  runtime/dev/src/lib.rs
Labels: needs review
