Repository ChainSafe/PINT, pull requests merged in 2021-06, with the labels that each got.

#79 feat(asset-index): implement complete withdrawal
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/traits.rs
Labels: needs review

#91 feat(benchmarks): add benchmarks and specific weights to all pallets
  Cargo.lock
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  pallets/asset-depository/Cargo.toml
  pallets/asset-depository/src/benchmarking.rs
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/local-treasury/Cargo.toml
  pallets/local-treasury/src/benchmarking.rs
  pallets/local-treasury/src/lib.rs
  pallets/local-treasury/src/mock.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/benchmarking.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/benchmarking.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/benchmarking.rs
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/mock.rs
  pallets/xcm-asset-support/Cargo.toml
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_asset_index.rs
  runtime/src/weights/pallet_committee.rs
  runtime/src/weights/pallet_local_treasury.rs
  runtime/src/weights/pallet_price_feed.rs
  runtime/src/weights/pallet_remote_asset_manager.rs
  runtime/src/weights/pallet_saft_registry.rs
Labels: approved

#104 feat(committee): add CommitteeMember origin for pallet committee
  node/src/chain_spec.rs
  pallets/committee/src/benchmarking.rs
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
  runtime/src/lib.rs
Labels: approved

#114 ci(cargo): use git cli and patch global git base url
  .cargo/config.toml
  .circleci/config.yml
  .dockerignore
  .gitignore
Labels: approved

#106 feat(asset-index): store initial price pair
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/traits.rs
Labels: approved

#107 chore: upgrade to polkadot 0.9.4
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/lib.rs
  node/src/main.rs
  node/src/service.rs
  pallets/asset-depository/Cargo.toml
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/types.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/lib.rs
  pallets/committee/src/types.rs
  pallets/committee/src/utils.rs
  pallets/local-treasury/Cargo.toml
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/saft-registry/Cargo.toml
  pallets/xcm-asset-support/Cargo.toml
  pallets/xcm-asset-support/src/lib.rs
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/lib.rs
  primitives/xcm-calls/src/staking.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  runtime/src/weights/mod.rs
  runtime/src/weights/pallet_chainlink_feed.rs
Labels: approved

#113 feat: integrate parachain collator pallet with session and cumulus aura
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: needs review

#100 feat: add assets pallet xcm bindings
  Cargo.lock
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/assets.rs
  primitives/xcm-calls/src/lib.rs
Labels: approved

#105 feat(asset-index): add AssetMetadata
  Cargo.lock
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/traits.rs
  pallets/asset-index/src/types.rs
  pallets/saft-registry/src/benchmarking.rs
  runtime/src/lib.rs
  runtime/src/weights/pallet_asset_index.rs
Labels: approved

#118 feat(js): complete PINT types
  js/e2e/src/runner.ts
  js/pint-types-bundle/chainlink.json
  js/pint-types-bundle/index.ts
  js/pint-types-bundle/tsconfig.json
Labels: approved

#117 refactor: extract asset registry to new primitives crate
  Cargo.lock
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/traits.rs
  pallets/asset-index/src/types.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/traits.rs
  primitives/primitives/Cargo.toml
  primitives/primitives/README.md
  primitives/primitives/src/lib.rs
  primitives/primitives/src/traits.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: needs changes

#120 feat: add pallet and runtime weights
  templates/pallet-weight-template.hbs
  templates/runtime-weight-template.hbs
Labels: needs review

#119 feat: implement staking related (un)bonding xcm calls
  Cargo.lock
  pallets/asset-depository/src/lib.rs
  pallets/asset-depository/src/traits.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/traits.rs
  primitives/primitives/src/traits.rs
  primitives/xcm-calls/src/staking.rs
Labels: approved

#124 feat(e2e): block async transactions in e2e tests
  js/e2e/package.json
  js/e2e/src/runner.ts
  node/src/cli.rs
Labels: approved

#132 chore: update polkadot-v0.9.5
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/service.rs
  pallets/asset-depository/Cargo.toml
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/mock.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/tests.rs
  pallets/local-treasury/Cargo.toml
  pallets/local-treasury/src/mock.rs
  pallets/price-feed/Cargo.toml
  pallets/price-feed/src/mock.rs
  pallets/remote-asset-manager/Cargo.toml
  pallets/saft-registry/Cargo.toml
  pallets/xcm-asset-support/Cargo.toml
  primitives/primitives/Cargo.toml
  primitives/xcm-calls/Cargo.toml
  primitives/xcm-calls/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: needs review

#133 chore: move xcm asset support to primitives
  primitives/xcm-asset-support/Cargo.toml
  primitives/xcm-asset-support/README.md
  primitives/xcm-asset-support/src/config.rs
  primitives/xcm-asset-support/src/lib.rs
  primitives/xcm-asset-support/src/traits.rs
Labels: approved

#134 Complete e2e tests for single call APIs
  js/e2e/index.ts
Labels: approved

#131 feat(assets): add multicurrency support
  Cargo.lock
  node/src/chain_spec.rs
  pallets/asset-depository/Cargo.toml
  pallets/asset-depository/README.md
  pallets/asset-depository/src/benchmarking.rs
  pallets/asset-depository/src/lib.rs
  pallets/asset-depository/src/mock.rs
  pallets/asset-depository/src/tests.rs
  pallets/asset-depository/src/traits.rs
  pallets/asset-depository/src/types.rs
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/types.rs
  primitives/primitives/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: approved

#136 E2E tests for pallet committee
  js/e2e/index.ts
  js/e2e/package.json
  js/e2e/src/config.ts
  js/e2e/src/runner.ts
  js/pint-types-bundle/package.json
  js/yarn.lock
Labels: approved

#135 refactor(asset-index): use user multicurrency accounts when adding assets
  Cargo.lock
  pallets/asset-index/src/benchmarking.rs
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/mock.rs
  pallets/asset-index/src/tests.rs
  pallets/asset-index/src/traits.rs
  pallets/asset-index/src/types.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/lib.rs
  pallets/saft-registry/src/mock.rs
  runtime/src/lib.rs
Labels: approved

#139 feat(e2e): add verify process in e2e tests
  .gitignore
  Cargo.lock
  js/e2e/index.ts
  js/e2e/package.json
  js/e2e/src/config.ts
  js/e2e/src/index.ts
  js/e2e/src/runner.ts
  js/e2e/src/util.ts
  js/pint-types-bundle/chainlink.json
  js/pint-types-bundle/index.ts
  js/pint-types-bundle/package.json
  js/yarn.lock
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/committee/src/lib.rs
  runtime/src/lib.rs
Labels: approved

#152 feat: optimise xcm asst management and monitor balances
  Cargo.lock
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  primitives/xcm-calls/src/staking.rs
  runtime/src/lib.rs
Labels: needs review

#154 feat: add xcm simulator support
  Cargo.lock
  pallets/remote-asset-manager/Cargo.toml
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/mock.rs
  pallets/remote-asset-manager/src/tests.rs
  test-utils/xcm-test-support/Cargo.toml
  test-utils/xcm-test-support/README.md
  test-utils/xcm-test-support/src/lib.rs
  test-utils/xcm-test-support/src/relay.rs
Labels: approved
