Repository ChainSafe/PINT, pull requests merged in 2021-04, with the labels that each got.

#35 chore(readme): updated readme
  README.md
Labels: chore, needs review

#38 Willem/committee add constituents
  pallets/committee/src/lib.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/tests.rs
  pallets/committee/src/types.rs
Labels: approved

#39 fix(deps): upstream rococo-v1
  .actrc
  .github/workflows/test-code.yml
  Cargo.lock
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  pallets/asset-index/src/mock.rs
  pallets/committee/src/mock.rs
  pallets/committee/src/types.rs
  pallets/local-treasury/src/lib.rs
  pallets/local-treasury/src/mock.rs
  pallets/saft-registry/src/mock.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: needs review

#40 Add price feed pallet
  Cargo.lock
  pallets/price-feed/Cargo.toml
  pallets/price-feed/README.md
  pallets/price-feed/src/lib.rs
  pallets/price-feed/src/mock.rs
  pallets/price-feed/src/tests.rs
  pallets/price-feed/src/traits.rs
  pallets/price-feed/src/types.rs
Labels: approved

#43 feat: add polkadot-launch config
  Cargo.lock
  README.md
  config.json
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
Labels: approved

#48 feat: add asset depository pallet
  Cargo.lock
  pallets/asset-depository/Cargo.toml
  pallets/asset-depository/README.md
  pallets/asset-depository/src/lib.rs
  pallets/asset-depository/src/mock.rs
  pallets/asset-depository/src/tests.rs
  pallets/asset-depository/src/traits.rs
  pallets/asset-depository/src/types.rs
Labels: approved

#49 ci(circleci): move forward to CircleCI
  .circleci/config.yml
  .github/workflows/docker.yml
  .github/workflows/test-code.yml
  Cargo.lock
  Dockerfile
Labels: approved

#55 feat(asset-index): introduce MultiAssetAdapter
  Cargo.lock
  pallets/asset-index/Cargo.toml
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/types.rs
  pallets/price-feed/src/lib.rs
Labels: approved

#56 feat(runtime): configure pint runtime
  Cargo.lock
  pallets/asset-index/src/lib.rs
  pallets/asset-index/src/types.rs
  pallets/committee/Cargo.toml
  pallets/committee/src/lib.rs
  pallets/committee/src/types.rs
  pallets/remote-asset-manager/src/lib.rs
  pallets/remote-asset-manager/src/traits.rs
  pallets/saft-registry/Cargo.toml
  pallets/saft-registry/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
Labels: approved, enhancement

#61 ci(docker): hotfix the trigger of publishing docker images by tags
  .circleci/config.yml
Labels: chore, needs review
